# fly.toml app configuration file generated for rust-axum-tailwind-htmx-todo on 2024-02-11T12:03:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rust-axum-tailwind-htmx-todo'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
